# 1. Use Java with Maven
FROM maven:3.9.4-eclipse-temurin-17-alpine AS build

# 2. Set workdir & copy project
WORKDIR /app
COPY . .

# 3. Build project
RUN mvn clean package -DskipTests

# 4. Run JAR
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
